### ISSUE TITLE
TOO MANY BUGS

### ISSUE THREAD

**Issue by Devon7** [zodmaner/trivial-mmap#3]
• Examples don't compile
• operates at compile/macroexpansion time instead of execution time
• posix munmap called with wrong args
… and that's just at first glance.

**Comment by zodmaner** [comment]
Hi! Thanks for noticing the glaring error! I wrote this library years ago and was in the middle of refactoring and implementing a new high-level interface for it when real-life obligations hit hard. So much so that I sorta forgot to update the example to match the changes.

Anyway, I've updated the examples to match the new interface/API, and also fix the `munmap-file` call with wrong arguments.

I've also added examples where you can use the library without relying on the helper macro, if you so wish. (Although the `with-mmap-file` macro is just an analogue to the `with-open-file` macro that is part of the Common Lisp standard, and is just another `with-*` macros that are so common in many libraries, that I don't feel there was any need to discourage people from using it).

Anyway, thanks for the bug report!
